"""added state_diff

Revision ID: 508c2524fd5b
Revises: 10f48d555d4a
Create Date: 2018-06-01 10:08:57.279597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508c2524fd5b'
down_revision = '10f48d555d4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state_diff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_number', sa.Numeric(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('transaction_hash', sa.String(length=66), nullable=True),
    sa.Column('transaction_index', sa.Numeric(), nullable=True),
    sa.Column('address', sa.String(length=42), nullable=True),
    sa.Column('balance_from', sa.Numeric(), nullable=True),
    sa.Column('balance_to', sa.Numeric(), nullable=True),
    sa.Column('nonce_from', sa.Integer(), nullable=True),
    sa.Column('nonce_to', sa.Integer(), nullable=True),
    sa.Column('code_from', sa.Text(), nullable=True),
    sa.Column('code_to', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['block_number'], ['blocks.block_number'], ),
    sa.ForeignKeyConstraint(['transaction_hash'], ['transactions.transaction_hash'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_state_diff_address'), 'state_diff', ['address'], unique=False)
    op.create_index(op.f('ix_state_diff_transaction_hash'), 'state_diff', ['transaction_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_state_diff_transaction_hash'), table_name='state_diff')
    op.drop_index(op.f('ix_state_diff_address'), table_name='state_diff')
    op.drop_table('state_diff')
    # ### end Alembic commands ###
